name: test_drag_drop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  animations: ^2.0.7
  google_fonts: any
  json_annotation:
  http: ^0.13.5
  dio: any
  uuid: ^3.0.7
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation:

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/